.TH UNDERWORLD 6
.SH NAME
underworld \- plays the game Underworld
.SH SYNOPSIS
.B underworld
.I [-story folder]
.SH DESCRIPTION
Underworld is an open-source simulator of the student 
life at the Tula State University, in which a player must 
dominate other students and fight the League of evil lecturers 
to get the degree.
.SH OPTIONS
.TP
\fB\-story folder\fP
Specify directory where to story scripts from.

.SH AUTHORS
underworld is developed by Underworld Assocation <underworld.association@gmail.com>.

This manpage was written by Roman Chistokhodov.
