.TH UNDERWORLD 6
.SH НАЗВАНИЕ
underworld \- играть в Underworld
.SH 
.B underworld
.I [-story folder]
.SH DESCRIPTION
Underworld - это открытый симулятор студенческой жизни 
в Тульском государственном университете, в котором игрок должен
соперничать с другими студентами и бороться со злыми преподавателями,
чтобы дожить до выпускного.
.SH OPTIONS
.TP
\fB\-story folder\fP
Указать папку, откуда загружать сценарий истории.

.SH AUTHORS
underworld разработан группой Underworld Assocation <underworld.association@gmail.com>.

Эту справочную страницу написал Roman Chistokhodov.
